services:

  maskforge-postgres:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maskforge-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data

  maskforge-redis:
    image: redis:7
    ports:
      - "26379:6379"

  maskforge-app:
    build: .
    working_dir: /app
    command: >
      sh -c "aerich upgrade && python -m uvicorn app.main:app --host 0.0.0.0 --port 8808"
    ports:
      - "9909:8808"
    restart: always
    env_file:
      - .env
    depends_on:
      - maskforge-postgres
      - maskforge-minio
      - maskforge-redis

  maskforge-worker:
    build: .
    working_dir: /app
    command:
      celery -A app.main.celery_app worker -l info
    env_file:
      - .env
    depends_on:
      - maskforge-redis
      - maskforge-postgres


volumes:
  postgres_data:
  minio_data:
